Update to docs to reflect current status of project
 - small change to linting script to deal with "python3" "python" name confusion
 - addressed accidental name inclusion (thank you @exachixkitsune !)
 - added details as to how to run linters and other utility scripts on windows (via git  sh/git bash)
 - tested new install instructions working

diff --git a/tools/path b/tools/path
--- a/tools/path
+++ b/tools/path
@@ -4,7 +4,16 @@
 #
 # SPDX-License-Identifier: BSD-2-Clause
 
-PYTHON=${PYTHON:-python3}
+if ! command -v python3 &> /dev/null
+then
+    echo "python3 could not be found"
+    echo "You may be on windows - trying with python not python3"
+    echo "BEWARE! You might be trying to run with python2 - this will fail pretty quick if so"
+    PYTHON=${PYTHON:-python}
+else
+    PYTHON=${PYTHON:-python3}
+fi
+
 readonly PYTHON
 
 PYTHONPATH="$("$PYTHON" src/mewbot/tools/path.py)"
